# Generated by Django 3.1.3 on 2021-01-12 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieCrime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, null=True)),
                ('prenom', models.CharField(max_length=50, null=True)),
                ('date_naissance', models.DateField(max_length=50, null=True)),
                ('lieu_naissance', models.CharField(max_length=30, null=True)),
                ('lieu_de_residence', models.CharField(max_length=30, null=True)),
                ('photo', models.ImageField(null=True, upload_to='media/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Antecedent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('date_des_faits', models.DateTimeField(null=True)),
                ('categories', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='antecedent.categoriecrime')),
                ('personne', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='antecedent.personne')),
            ],
        ),
    ]
