# Generated by Django 3.1.3 on 2021-01-14 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antecedent', '0002_auto_20210112_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antecedent',
            name='date_des_faits',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='personne',
            name='date_naissance',
            field=models.DateField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='personne',
            name='lieu_de_residence',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='personne',
            name='lieu_naissance',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='personne',
            name='nom',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='personne',
            name='prenom',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
